// Short interview excerpts. Translations are identified in the visible source label.
const quote = (text, author, source, translated = false) => ({
  text, author, source, work: translated ? 'Fragmento · traducción al español' : 'Fragmento · fuente original',
});
const ilia = (text, source, translated = false) => quote(text, 'Ilia Topuria', source, translated);
const sources = {
  topuriaTVE: 'https://www.rtve.es/deportes/20240404/entrevista-ilia-topuria-tve/16045081.shtml',
  topuriaTraining: 'https://www.antena3.com/noticias/deportes/ilia-topuria-desvela-antena-3-sus-secretos-ser-invencible_2025032767e572de8ba0d30001ffbf5d.html',
  topuriaMind: 'https://www.antena3.com/programas/el-hormiguero/entrevista/ilia-topuria-motivacion-filosofia-vida-miedo-poder-ver-mejor-version_20231009652462ee90d39d00010c1cf9.html',
  topuriaDream: 'https://www.antena3internacional.com/programas/el-hormiguero/noticias/ilia-topuria-en-el-hormiguero-30-me-tengo-que-exigir-todo-el-tiempo-porque-el-premio-es-mi-sueno_2024022765ddc3bb344c980001c30123.html',
  topuriaPreparation: 'https://www.antena3internacional.com/programas/el-hormiguero/noticias/ilia-topuria-vuelve-a-el-hormiguero-tras-su-victoria-contra-max-holloway-si-nadie-lo-ha-hecho-yo-sere-el-primero-en-hacerlo_2024111567374b6fb747ad00018361ae.html',
  topuriaDoubts: 'https://www.antena3.com/programas/el-hormiguero/entrevista/dudas-son-impulso-ilia-topuria-desvela-secreto-combatir-miedo_2024111467366d30b747ad0001817696.html',
  topuriaStart: 'https://www.antena3.com/noticias/deportes/le-comparan-con-mcgregor_202012125fd4e847d4aa1e00012b47a5.html',
  topuriaSER: 'https://cadenaser.com/cataluna/2024/09/20/ilia-topuria-yo-respeto-a-todos-mis-rivales-como-profesionales-pero-yo-estoy-luchando-por-mis-suenos-sercat/',
  topuriaCritics: 'https://www.antena3.com/programas/el-hormiguero/invitados/ilia-topuria_20250508681c487d5d71dc778a9cf6d2.html',
  topuriaDirection: 'https://www.telecinco.es/noticias/deportes/20240228/ilia-topuria-influencia-campeon-ufc_18_011820061.html',
  federer: 'https://home.dartmouth.edu/news/2024/06/2024-commencement-address-roger-federer',
  felix: 'https://worldathletics.org/women-in-athletics/news/allyson-felix-usa-sprinter-mother-olympics-20',
  serena: 'https://www.wtatennis.com/news/1447037/im-a-fighter-i-never-give-up-serena-quells-teen-juvan-at-wimbledon',
  nadal: 'https://www.rtve.es/deportes/20130920/nadal-gusta-ganar-con-esfuerzo/748368.shtml',
  nadalSpeech: 'https://comunicacion.usal.es/filessp/Doctorado_honoris_causa_a_Rafael_Nadal.pdf',
  kipchoge: 'https://citiusmag.com/articles/eliud-kipchoge-2025-interview',
  kipchogeLimits: 'https://worldathletics.org/awards/news/eliud-kipchoge-athlete-of-year-2019',
  kipchogeWisdom: 'https://worldathletics.org/spikes/news/words-of-wisdom-eliud-kipchoge',
  rudisha: 'https://worldathletics.org/spikes/news/david-rudishas-words-of-wisdom',
  phillips: 'https://worldathletics.org/spikes/news/dwight-phillips-words-of-wisdom',
  williamsMills: 'https://worldathletics.org/spikes/news/novlene-williams-mills-words-of-wisdom',
  biles: 'https://apnews.com/article/1c7d4352a67c062bcc65fb7f56c9a1a3',
  sabalenka: 'https://www.wtatennis.com/players/320760/-aryna-sabalenka-',
  petkovic: 'https://www.wtatennis.com/news/2441012/petkovic-relishing-every-moment-im-seeing-the-finish-line',
  swiatek: 'https://www.usopen.org/en_US/news/articles/2024-05-20/iga_swiatek_rolls_to_rome_title_cementing_status_as_roland_garros_favorite.html',
  alcaraz: 'https://www.rolandgarros.com/en-us/article/rg2025-carlos-alcaraz-2024-champion-interview-magazine-career-ambition',
  coventry: 'https://newsroom.olympics.com/record/3169/media_id/6799',
};

const TOPURIA_QUOTES = [
  ilia('Siempre he creído en mí y he estado preparado para lo que pudiera pasar en el camino.', sources.topuriaTVE),
  ilia('Nadie me ha regalado nada.', sources.topuriaTVE),
  ilia('Entreno mis pensamientos de no darme por vencido en ningún momento de mi vida.', sources.topuriaTraining),
  ilia('El deporte es algo que nadie puede hacer por ti.', sources.topuriaTraining),
  ilia('Me da miedo no poder ver mi mejor versión.', sources.topuriaMind),
  ilia('He preparado mi cuerpo y mi mente para ser el maestro de mi destino.', sources.topuriaMind),
  ilia('Tienes que seguir porque el premio es tu sueño.', sources.topuriaDream),
  ilia('Hemos escrito historia, pero es el momento de forjar la leyenda.', sources.topuriaDream),
  ilia('Si nadie lo ha hecho, seré el primero en hacerlo.', sources.topuriaPreparation),
  ilia('La única forma de vencer el miedo es a través de la preparación.', sources.topuriaPreparation),
  ilia('Las dudas son un impulso.', sources.topuriaDoubts),
  ilia('Sé que iba a llegar y todavía soy capaz de más.', sources.topuriaStart),
  ilia('Cada sacrificio tiene su recompensa.', sources.topuriaStart),
  ilia('Yo estoy luchando por mis sueños.', sources.topuriaSER),
  ilia('Con el trabajo todo se puede conseguir en la vida.', sources.topuriaSER, true),
  ilia('Toda crítica es una confesión. Lo que ves en los demás es porque primero lo ves en ti.', sources.topuriaCritics),
  ilia('Da igual de dónde vengas si sabes hacia dónde vas.', sources.topuriaDirection),
];

const OTHER_ATHLETES = [
  quote('Lo de «sin esfuerzo» es un mito.', 'Roger Federer', sources.federer, true),
  quote('La disciplina también es un talento.', 'Roger Federer', sources.federer, true),
  quote('Confiar en ti es un talento.', 'Roger Federer', sources.federer, true),
  quote('Adáptate y crece.', 'Roger Federer', sources.federer, true),
  quote('Di tu verdad.', 'Allyson Felix', sources.felix, true),
  quote('Crea cambio.', 'Allyson Felix', sources.felix, true),
  quote('Haz lo que te apasiona.', 'Allyson Felix', sources.felix, true),
  quote('Soy una luchadora y nunca me rindo.', 'Serena Williams', sources.serena, true),
  quote('Me gusta la presión.', 'Serena Williams', sources.serena, true),
  quote('Aprender de cada punto.', 'Serena Williams', sources.serena, true),
  quote('Hay que esforzarse día a día y levantarse con actitud positiva para cambiar la situación.', 'Rafael Nadal', sources.nadal),
  quote('Me gusta ganar con esfuerzo.', 'Rafael Nadal', sources.nadal),
  quote('Nada se consigue sin esfuerzo diario.', 'Rafael Nadal', sources.nadalSpeech),
  quote('Mi única ilusión era mejorar cada día.', 'Rafael Nadal', sources.nadalSpeech),
  quote('Defino el éxito como inspiración.', 'Eliud Kipchoge', sources.kipchoge, true),
  quote('Lo que tengo en mente es inspirar, unir a las personas.', 'Eliud Kipchoge', sources.kipchoge, true),
  quote('Ningún ser humano está limitado.', 'Eliud Kipchoge', sources.kipchogeLimits, true),
  quote('Siempre acepto la derrota con elegancia porque el atletismo es un deporte social y pacífico.', 'Eliud Kipchoge', sources.kipchogeWisdom, true),
  quote('Para triunfar, todo se basa en trabajo duro, disciplina y determinación.', 'David Rudisha', sources.rudisha, true),
  quote('El trabajo duro vence al talento cuando el talento no trabaja duro.', 'Dwight Phillips', sources.phillips, true),
  quote('Sentía que podía trabajar más que cualquiera.', 'Dwight Phillips', sources.phillips, true),
  quote('No hay soluciones rápidas en el atletismo.', 'Novlene Williams-Mills', sources.williamsMills, true),
  quote('Quiero ver hasta dónde puedo llegar.', 'Simone Biles', sources.biles, true),
  quote('Quiero ver de qué soy todavía capaz.', 'Simone Biles', sources.biles, true),
  quote('Nunca te rindas; mantente agresiva, mantén el hambre y exígete, pase lo que pase en tu vida.', 'Aryna Sabalenka', sources.sabalenka, true),
  quote('Quiero salir, luchar cada punto y creer en mí.', 'Andrea Petkovic', sources.petkovic, true),
  quote('Haré todo paso a paso y veremos.', 'Iga Świątek', sources.swiatek, true),
  quote('Hay que tener talento, obviamente, pero no te lleva a ninguna parte si no trabajas.', 'Carlos Alcaraz', sources.alcaraz, true),
  quote('Siempre aprender, siempre mejorar, nunca quedarse quieto.', 'Kirsty Coventry', sources.coventry, true),
];

// Spread Topuria's excerpts throughout the rotation instead of grouping one author.
export const ATHLETE_QUOTES = OTHER_ATHLETES.flatMap((entry, index) => [
  ...(TOPURIA_QUOTES[index] ? [TOPURIA_QUOTES[index]] : []), entry,
]);
