const DAILY_QUOTES = [
  { text: 'No es que tengamos poco tiempo, sino que perdemos mucho.', author: 'Séneca' },
  { text: 'Bien hecho es mejor que bien dicho.', author: 'Benjamin Franklin' },
  { text: 'Primero dite a ti mismo quién quieres ser; luego, haz lo que debes hacer.', author: 'Epicteto' },
  { text: 'La suerte favorece a la mente preparada.', author: 'Louis Pasteur' },
  { text: 'Nuestras dudas nos hacen perder el bien que podríamos alcanzar por miedo a intentarlo.', author: 'William Shakespeare' },
  { text: 'La vida es larga si sabes aprovecharla.', author: 'Séneca' },
  { text: 'La obra maestra del ser humano es vivir con propósito.', author: 'Benjamin Franklin' },
  { text: 'No son las cosas las que nos inquietan, sino nuestra opinión sobre ellas.', author: 'Epicteto' },
  { text: 'Nada es difícil para quien está dispuesto.', author: 'Epicteto' },
  { text: 'No esperes que los acontecimientos ocurran como deseas; desea que ocurran como ocurren.', author: 'Epicteto' },
  { text: 'El impedimento a la acción impulsa la acción; lo que se interpone en el camino se vuelve el camino.', author: 'Marco Aurelio' },
  { text: 'Tienes poder sobre tu mente, no sobre los acontecimientos externos.', author: 'Marco Aurelio' },
  { text: 'No pierdas más tiempo discutiendo cómo debe ser una persona buena. Sé una.', author: 'Marco Aurelio' },
  { text: 'La felicidad de tu vida depende de la calidad de tus pensamientos.', author: 'Marco Aurelio' },
  { text: 'Lo que no es bueno para la colmena tampoco lo es para la abeja.', author: 'Marco Aurelio' },
  { text: 'Ningún viento es favorable para quien no sabe a qué puerto se dirige.', author: 'Séneca' },
  { text: 'Mientras enseñamos, aprendemos.', author: 'Séneca' },
  { text: 'Empieza a vivir de inmediato y cuenta cada día como una vida aparte.', author: 'Séneca' },
  { text: 'La dificultad muestra lo que las personas son.', author: 'Epicteto' },
  { text: 'Primero aprende el significado de lo que dices y luego habla.', author: 'Epicteto' },
  { text: 'El secreto para salir adelante es empezar.', author: 'Mark Twain' },
  { text: 'El futuro depende de lo que hagas hoy.', author: 'Mahatma Gandhi' },
  { text: 'La mejor forma de encontrar tu camino es crearlo.', author: 'George Bernard Shaw' },
  { text: 'Nuestra mayor gloria no está en no caer, sino en levantarnos cada vez que caemos.', author: 'Confucio' },
  { text: 'No importa lo lento que avances, siempre que no te detengas.', author: 'Confucio' },
  { text: 'Un viaje de mil kilómetros comienza con un solo paso.', author: 'Lao-Tsé' },
  { text: 'Quien mueve una montaña comienza por quitar las piedras pequeñas.', author: 'Proverbio chino' },
  { text: 'La paciencia es amarga, pero su fruto es dulce.', author: 'Jean-Jacques Rousseau' },
  { text: 'El éxito es la suma de pequeños esfuerzos repetidos cada día.', author: 'Robert Collier' },
  { text: 'La energía y la perseverancia conquistan todas las cosas.', author: 'Benjamin Franklin' },
  { text: 'El tiempo perdido nunca se recupera.', author: 'Benjamin Franklin' },
  { text: 'La diligencia es la madre de la buena fortuna.', author: 'Benjamin Franklin' },
  { text: 'Quien es bueno poniendo excusas rara vez es bueno en otra cosa.', author: 'Benjamin Franklin' },
  { text: 'Nada grande se ha logrado sin entusiasmo.', author: 'Ralph Waldo Emerson' },
  { text: 'Termina cada día y déjalo atrás; hiciste lo que pudiste.', author: 'Ralph Waldo Emerson' },
  { text: 'La única manera de tener un amigo es serlo.', author: 'Ralph Waldo Emerson' },
  { text: 'Ve con confianza en dirección a tus sueños.', author: 'Henry David Thoreau' },
  { text: 'El precio de cualquier cosa es la cantidad de vida que entregas por ella.', author: 'Henry David Thoreau' },
  { text: 'Solo cuando nos perdemos empezamos a comprendernos.', author: 'Henry David Thoreau' },
  { text: 'La vida solo puede comprenderse mirando hacia atrás, aunque se vive hacia adelante.', author: 'Søren Kierkegaard' },
  { text: 'Saber no basta; hay que aplicarlo. Querer no basta; hay que hacerlo.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Nada vale más que este día.', author: 'Johann Wolfgang von Goethe' },
  { text: 'El talento se cultiva en la calma; el carácter, en la corriente de la vida.', author: 'Johann Wolfgang von Goethe' },
  { text: 'La acción es la clave fundamental de todo éxito.', author: 'Pablo Picasso' },
  { text: 'Todo lo que puedas hacer o soñar, comiénzalo.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Nuestra vida es lo que nuestros pensamientos hacen de ella.', author: 'Marco Aurelio' },
  { text: 'La fortuna ayuda a quienes se atreven.', author: 'Virgilio' },
  { text: 'Carpe diem: aprovecha el día.', author: 'Horacio' },
  { text: 'La gota horada la piedra, no por su fuerza, sino por su constancia.', author: 'Ovidio' },
  { text: 'No es en las estrellas donde está nuestro destino, sino en nosotros mismos.', author: 'William Shakespeare' },
  { text: 'Sabemos lo que somos, pero no lo que podemos llegar a ser.', author: 'William Shakespeare' },
  { text: 'Presta oído a todos, pero tu voz a pocos.', author: 'William Shakespeare' },
  { text: 'No hay nada bueno ni malo; el pensamiento lo hace así.', author: 'William Shakespeare' },
  { text: 'El mundo entero es un escenario.', author: 'William Shakespeare' },
  { text: 'La fortuna favorece a la mente preparada.', author: 'Louis Pasteur' },
  { text: 'La imaginación es más importante que el conocimiento.', author: 'Albert Einstein' },
  { text: 'En medio de la dificultad yace la oportunidad.', author: 'Albert Einstein' },
  { text: 'Quien nunca ha cometido un error nunca ha intentado algo nuevo.', author: 'Albert Einstein' },
  { text: 'La creatividad es la inteligencia divirtiéndose.', author: 'Albert Einstein' },
  { text: 'No cuentes los días; haz que los días cuenten.', author: 'Muhammad Ali' },
  { text: 'Imposible es solo una opinión.', author: 'Muhammad Ali' },
  { text: 'Si puedes soñarlo, puedes hacerlo.', author: 'Walt Disney' },
  { text: 'La forma de empezar es dejar de hablar y empezar a hacer.', author: 'Walt Disney' },
  { text: 'El éxito es ir de fracaso en fracaso sin perder el entusiasmo.', author: 'Winston Churchill' },
  { text: 'Nunca ceder, nunca ceder, nunca, nunca, nunca.', author: 'Winston Churchill' },
  { text: 'Haz lo que puedas, con lo que tengas, donde estés.', author: 'Theodore Roosevelt' },
  { text: 'Cree que puedes y ya habrás recorrido la mitad del camino.', author: 'Theodore Roosevelt' },
  { text: 'El futuro pertenece a quienes creen en la belleza de sus sueños.', author: 'Eleanor Roosevelt' },
  { text: 'Nadie puede hacerte sentir inferior sin tu consentimiento.', author: 'Eleanor Roosevelt' },
  { text: 'Parece imposible hasta que se hace.', author: 'Nelson Mandela' },
  { text: 'Siempre parece imposible hasta que está hecho.', author: 'Nelson Mandela' },
  { text: 'La educación es el arma más poderosa para cambiar el mundo.', author: 'Nelson Mandela' },
  { text: 'Haz hoy algo que tu yo futuro te agradezca.', author: 'Brota' },
  { text: 'Paso a paso también se llega lejos.', author: 'Brota' },
  { text: 'Un comienzo pequeño sigue siendo un comienzo.', author: 'Brota' },
  { text: 'No tienes que verlo todo claro para dar el siguiente paso.', author: 'Brota' },
  { text: 'Lo constante, aunque pequeño, transforma lo grande.', author: 'Brota' },
  { text: 'Cada día ofrece otra oportunidad para intentarlo.', author: 'Brota' },
  { text: 'La práctica de hoy construye la confianza de mañana.', author: 'Brota' },
  { text: 'Avanzar despacio sigue siendo avanzar.', author: 'Brota' },
  { text: 'La disciplina de hoy es la libertad de mañana.', author: 'Brota' },
  { text: 'Un paso valiente puede cambiar el rumbo de todo un día.', author: 'Brota' },
  { text: 'Hazlo con miedo, pero hazlo.', author: 'Brota' },
  { text: 'La constancia convierte los intentos en logros.', author: 'Brota' },
  { text: 'No hace falta hacerlo perfecto; hace falta empezar.', author: 'Brota' },
  { text: 'Tu ritmo también es un ritmo válido.', author: 'Brota' },
  { text: 'Las raíces crecen antes de que aparezcan las flores.', author: 'Brota' },
  { text: 'Lo que cuidas con paciencia termina creciendo.', author: 'Brota' },
  { text: 'La pausa también forma parte del progreso.', author: 'Brota' },
  { text: 'Descansar es prepararse para volver con energía.', author: 'Brota' },
  { text: 'La concentración transforma el tiempo en avance.', author: 'Brota' },
  { text: 'Una tarea a la vez; una victoria a la vez.', author: 'Brota' },
  { text: 'Lo importante no es correr, sino continuar.', author: 'Brota' },
  { text: 'El esfuerzo de hoy es la semilla del logro de mañana.', author: 'Brota' },
  { text: 'Haz sitio para lo que de verdad importa.', author: 'Brota' },
  { text: 'Cada minuto de atención es un regalo para tu futuro.', author: 'Brota' },
  { text: 'Empieza donde estás, con lo que tienes.', author: 'Brota' },
  { text: 'La motivación te pone en marcha; el hábito te mantiene.', author: 'Brota' },
  { text: 'Un día difícil no borra todo lo que has avanzado.', author: 'Brota' },
  { text: 'La paciencia también es una forma de valentía.', author: 'Brota' },
  { text: 'El progreso no siempre hace ruido.', author: 'Brota' },
  { text: 'Vuelve a empezar; ahora sabes un poco más.', author: 'Brota' },
  { text: 'Los grandes cambios caben en pequeñas decisiones.', author: 'Brota' },
  { text: 'Tu mejor esfuerzo de hoy es suficiente para hoy.', author: 'Brota' },
  { text: 'La atención es el comienzo de toda creación.', author: 'Brota' },
  { text: 'Construye el día que quieres vivir.', author: 'Brota' },
  { text: 'No subestimes lo que puedes lograr en unos minutos de enfoque.', author: 'Brota' },
  { text: 'Cada intento te acerca a descubrir cómo hacerlo.', author: 'Brota' },
  { text: 'El camino aparece cuando das el primer paso.', author: 'Brota' },
  { text: 'Celebra el avance, incluso cuando todavía quede camino.', author: 'Brota' },
  { text: 'Hoy basta con hacer lo siguiente que toca.', author: 'Brota' },
  { text: 'La calma también puede ser poderosa.', author: 'Brota' },
  { text: 'Cuida tu energía y úsala en lo que valoras.', author: 'Brota' },
  { text: 'Deja que la constancia haga su trabajo.', author: 'Brota' },
  { text: 'Tu futuro se construye con lo que haces ahora.', author: 'Brota' },
  { text: 'No esperes el momento perfecto; haz perfecto este momento.', author: 'Brota' },
  { text: 'Un objetivo claro vuelve más sencillo el siguiente paso.', author: 'Brota' },
  { text: 'La voluntad crece cada vez que cumples una promesa pequeña.', author: 'Brota' },
  { text: 'Deja que tu curiosidad sea más grande que tu miedo.', author: 'Brota' },
  { text: 'Hoy también puedes elegir empezar de nuevo.', author: 'Brota' },
  { text: 'Con paciencia y cuidado, lo pequeño florece.', author: 'Brota' },
  { text: 'Avanza con intención; lo demás puede esperar.', author: 'Brota' },
  { text: 'Haz de tu atención un lugar donde las ideas puedan crecer.', author: 'Brota' },
  { text: 'Lo que haces repetidamente va dando forma a tu camino.', author: 'Brota' },
  { text: 'El descanso no es rendirse; es recuperar fuerzas.', author: 'Brota' },
  { text: 'Cada sesión terminada es una prueba de que puedes confiar en ti.', author: 'Brota' },
  { text: 'No necesitas tener ganas para dar un paso pequeño.', author: 'Brota' },
  { text: 'Sé paciente con el proceso y firme con tu propósito.', author: 'Brota' },
  { text: 'Hazlo simple: respira, elige, empieza.', author: 'Brota' },
  { text: 'La perseverancia es volver a intentarlo con lo aprendido.', author: 'Brota' },
  { text: 'Un poco de progreso cada día suma mucho con el tiempo.', author: 'Brota' },
  { text: 'Permítete aprender mientras avanzas.', author: 'Brota' },
  { text: 'La concentración de ahora es el alivio de después.', author: 'Brota' },
  { text: 'Puedes empezar otra vez tantas veces como haga falta.', author: 'Brota' },
  { text: 'Hazlo por la persona en la que te estás convirtiendo.', author: 'Brota' },
  { text: 'Los hábitos pequeños abren puertas grandes.', author: 'Brota' },
  { text: 'Aunque hoy avances poco, sigues más adelante que ayer.', author: 'Brota' },
  { text: 'Dedica este rato a aquello que quieres ver crecer.', author: 'Brota' },
  { text: 'El enfoque es decir sí a una cosa por ahora.', author: 'Brota' },
  { text: 'La paciencia hace posible sostener el esfuerzo.', author: 'Brota' },
  { text: 'Empieza antes de sentirte listo; la claridad llega haciendo.', author: 'Brota' },
  { text: 'Que tu siguiente paso sea pequeño y verdadero.', author: 'Brota' },
  { text: 'El trabajo hecho con cuidado deja huella.', author: 'Brota' },
  { text: 'Tu esfuerzo cuenta, incluso cuando nadie lo ve.', author: 'Brota' },
  { text: 'Hoy no necesitas resolverlo todo; solo comenzar.', author: 'Brota' },
  { text: 'La esperanza también se practica.', author: 'Brota' },
  { text: 'Haz una pausa, vuelve a respirar y continúa.', author: 'Brota' },
  { text: 'La constancia es una forma silenciosa de creer en ti.', author: 'Brota' },
  { text: 'Elige una cosa y regálale toda tu atención.', author: 'Brota' },
  { text: 'Cada día que lo intentas, fortaleces el hábito.', author: 'Brota' },
  { text: 'No compares tu capítulo uno con el capítulo veinte de alguien más.', author: 'Brota' },
  { text: 'Descubre cuánto puedes avanzar si empiezas ahora.', author: 'Brota' },
  { text: 'Haz espacio para equivocarte y seguir aprendiendo.', author: 'Brota' },
  { text: 'La meta se acerca cada vez que vuelves al camino.', author: 'Brota' },
  { text: 'Lo que hoy parece pequeño puede ser importante con el tiempo.', author: 'Brota' },
  { text: 'Respeta tu proceso; cada crecimiento tiene su estación.', author: 'Brota' },
  { text: 'Tu atención es limitada: entrégala con intención.', author: 'Brota' },
  { text: 'Empieza con calma y termina con orgullo.', author: 'Brota' },
  { text: 'La mejor forma de avanzar es volver a lo esencial.', author: 'Brota' },
  { text: 'Haz que este rato cuente para ti.', author: 'Brota' },
];

export function getDailyQuote(date = new Date()) {
  const localMidnight = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  const dayNumber = Math.floor(localMidnight.getTime() / 86_400_000);
  return DAILY_QUOTES[((dayNumber % DAILY_QUOTES.length) + DAILY_QUOTES.length) % DAILY_QUOTES.length];
}
